player_level_requirement: 80

database:
  host: localhost
  port: 3306
  name: fishing
  user: root
  password: ""

qte:
  clicks: 1
  start_delay_ms: [650, 1100]
  window_len_ms: [350, 700]

anti_cheat:
  sample_size: 5
  tolerance_ms: 30
  action: CANCEL # or REDUCE
  drop_multiplier: 0.5

economy:
  currency_symbol: "$"
  quicksell_tax: 0.0
  global_multiplier: 1.0

warps:
  - key: fishing_main
    type: COMMAND
    command: "warp fishing_pool %player%"
  - key: oceanic_pier
    type: COMMAND
    command: "warp oceanic_pier %player%"
  - key: sunken_grotto
    type: COORDS
    world: world
    x: 123.5
    y: 64
    z: -210.5

rare_weight_scaling:
  RUNE:
    mode: EXP
    beta: 0.007
  TREASURE:
    mode: EXP
    beta: 0.006
  FISH_PREMIUM:
    mode: POLY
    alpha: 0.015
    k: 0.9
