player_level_requirement: 80

database:
  host: localhost
  port: 3306
  name: fishing
  user: root
  password: ""

qte:
  chance: 0.25
  duration_ms: 1000

anti_cheat:
  sample_size: 5
  tolerance_ms: 30
  action: CANCEL # or REDUCE
  drop_multiplier: 0.5

economy:
  currency_symbol: "$"
  quicksell_tax: 0.0
  global_multiplier: 1.0

leveling:
  exp_base: 50
  exp_coeff: 0.09
  exp_power: 2.3

exp_gain:
  fish_base: 9
  fish_per_kg: 0.5
  chest_base: 22
  rune_base: 40
  treasure_base: 80

warps:
  - key: fishing_main
    type: COMMAND
    command: "warp fishing_pool %player%"
  - key: oceanic_pier
    type: COMMAND
    command: "warp oceanic_pier %player%"
  - key: sunken_grotto
    type: COORDS
    world: world
    x: 123.5
    y: 64
    z: -210.5

category_weights:
  FISH: 9600
  FISHERMAN_CHEST: 300
  RUNE: 80
  TREASURE: 8

category_scaling:
  FISH:
    mode: EXP
    beta: 0.0006
  FISHERMAN_CHEST:
    mode: EXP
    beta: 0.0025
  RUNE:
    mode: EXP
    beta: 0.0020
  TREASURE:
    mode: EXP
    beta: 0.0040
