player_level_requirement: 80

database:
  host: localhost
  port: 3306
  name: fishing
  user: root
  password: ""

qte:
  clicks: 1
  start_delay_ms: [650, 1100]
  window_len_ms: [350, 700]

anti_cheat:
  sample_size: 5
  tolerance_ms: 30
  action: CANCEL # or REDUCE
  drop_multiplier: 0.5

economy:
  currency_symbol: "$"
  quicksell_tax: 0.0
  global_multiplier: 1.0
  max_price: 10000.0

leveling:
  exp_base: 150
  growthA: 1.12
  growthB: 1.14
  growthC: 1.16

exp_gain:
  base: 8
  weight_factor: 0.4
  qte_bonus: 3

base_category_weights:
  FISH: 9500
  FISH_PREMIUM: 350
  RUNE: 80
  TREASURE: 50
  FISHERMAN_CHEST: 15
  MATERIAL: 5

warps:
  - key: fishing_main
    type: COMMAND
    command: "warp fishing_pool %player%"
  - key: oceanic_pier
    type: COMMAND
    command: "warp oceanic_pier %player%"
  - key: sunken_grotto
    type: COORDS
    world: world
    x: 123.5
    y: 64
    z: -210.5

rare_weight_scaling:
  RUNE:
    mode: EXP
    beta: 0.007
  TREASURE:
    mode: EXP
    beta: 0.006
  FISH_PREMIUM:
    mode: POLY
    alpha: 0.015
    k: 0.9
