name: FishingPlugin
main: org.maks.fishingPlugin.FishingPlugin
version: 0.0.1
api-version: 1.20
softdepend: [PlaceholderAPI, EliteLootbox, WorldGuard, Citizens]
commands:
  fishing:
    description: Fishing commands
    usage: /fishing
    permission: fishing.use
permissions:
  fishing.admin:
    description: Allows editing loot and quests
    default: op
