name: FishingPlugin
main: org.maks.fishingPlugin.FishingPlugin
version: 0.0.1
api-version: 1.20
commands:
  fishing:
    description: Fishing commands
    usage: /fishing sell|warp <key>|quest
    permission: fishing.use
