ALTER TABLE quest
    ADD COLUMN IF NOT EXISTS title VARCHAR(64) DEFAULT '';
ALTER TABLE quest
    ADD COLUMN IF NOT EXISTS lore TEXT;
ALTER TABLE quest
    ADD COLUMN IF NOT EXISTS goal_type VARCHAR(32) DEFAULT 'CATCH';
ALTER TABLE quest
    ADD COLUMN IF NOT EXISTS reward_type VARCHAR(32) DEFAULT 'MONEY';
ALTER TABLE quest
    ADD COLUMN IF NOT EXISTS reward_data TEXT;

