ALTER TABLE fishing_profile
    ADD COLUMN qs_earned BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN last_qte_sample VARBINARY(64),
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
